### ISSUE TITLE
Add simple semantic versioning

### ISSUE THREAD

**Issue by amazingrando** [fate-srd/fate-product-list#10]
By adding version numbers to this repo, other projects can know when this has been updated. I would find this useful for the Fate SRD product list page.

What do I mean by simple? Every change that is merged into `main` could increment it.

If we wanted to get fancy, we could change the major number (1.0.0) each time a product is added or removed and a minor number (0.1.0) for other edits. Enforcing this fancy version would require effort.

**Comment by johnhelmuth** [comment]
I think a simple incrementing integer would be sufficient. An alternative might be just to use the date.

I haven't set up any github actions, just skimmed the docs... seems like it might be possible to set up an action to add a git tag immediately after a merge to `main`.

**Comment by amazingrando** [comment]
Incrementing the version number in package.json would be great, since I have it installed as a package in the Fate SRD repo.

**Comment by szabba** [comment]
Thinking about this like a semvered API I'd expect something closer to:
- major version updates on removing a column,
- minor version updates on adding a column,
- patch updates on changes in row contests.

Since the CSV has a header I think it's feasible to treat column reodering as a patch change.

**Comment by johnhelmuth** [comment]
@amazingrando 
Would you want the version number to bump when a commit/merge with the required changes is pushed to main, or would you rather have a formal GitHub release trigger it?

I'm thinking that the best way to implement this is by adding some scripts to the repo to handle these cases, and trigger them via configuration in `package.json`... `npm version` does the version number change, including handling git tagging... and we can add some glue code to implement the logic about determining which level of the semver version to bump.

**Comment by johnhelmuth** [comment]
I agree with @szabba  that the changes in columns should trigger a major or minor version bump, as removing a column is more of a "breaking change" while adding a column is something that code that consumes this data can easily handle.

**Comment by amazingrando** [comment]
> Would you want the version number to bump when a commit/merge with the required changes is pushed to main, or would you rather have a formal GitHub release trigger it?

Pushed to `main` would be sufficient.

**Comment by johnhelmuth** [comment]
Because we don't have a stable ID for each product, it is very hard to determine the difference between "changing content of existing rows without reordering" and "Adding a new row", especially if adding a new row also included deleting an old row.

File t1.csv
```
title
ABB
ABC
ZZZZ
```
For example, in t1.csv if you change the second element to "XYZ" and save it as t2.csv, the list is still in order, but it looks like an item was dropped and another added.

File t2.csv
```
title
ABB
XYZ
ZZZZ
```

```
% diff t1.csv t2.csv
3c3
< ABC
---
> XYZ
```

If there is a stable ID that doesn't change when the title or the publisher changes, then you can tell that the element with id 2 changed.

File t3.csv
```
id,title
1,ABB
2,ABC
3,ZZZZ
```

File t4.csv
```
id,title
1,ABB
2,XYZ
3,ZZZZ
```

Because the second row's ID can be compared against the row with the same ID, you can tell that the product itself changed.

I think we go with the simple versioning (bump the version number every time a commit is merged to `main` where `fate-product-list.csv` has any changes, OR we add a stable unique ID of some sort, like a UUID or just a hash of the ORIGINAL publisher name and product title (and maybe product URL).

Since the column definitions are on the same line in every version of the file, it is easy to detect the column name changes, so that could be implemented easily.

It is possible I've got blinders on and am missing something, I am open to discussing this via chat or a voice call.

**Comment by szabba** [comment]
Besides the lack of IDs. I'm not sure @amazingrando 's proposition matches my understanding of semver.

> Major (1.0.0)—Adding a new row; Changing column order; Adding or removing a column.

I'm not sure in what world adding a row would break code relying on the CSV - which is the criterion for major updates under semver.

I could see a case where changing the column order would break code, but it's arguable that code shouldn't rely on that - that's what the labels in the first, header, row are for.

**Comment by johnhelmuth** [comment]
It’s my understanding that the version number will be used to determine if the change should be deployed or not, as much as whether it will break the code… so it makes sense to me that adding new products to the list would be a major bump, while fixing a typo, not as much.

**Comment by szabba** [comment]
Which is an OK thing to do! It's just that calling that semver it's confusing to people who understand semver, as per the spec, as a best-effort-approximation-of-whether-dependent-code-might-break.

**Comment by johnhelmuth** [comment]
I've decided to just implement a simple incremental version number triggered by any change to the product list file when a PR is merged.  I am testing this out now on my repo and will do a PR on that today or tomorrow,  I hope.

**Comment by johnhelmuth** [comment]
@amazingrando please review that pull request, I don't want to just merge it without someone else looking at it.

**Comment by amazingrando** [comment]
Reviewed and it works perfectly!

**Comment by johnhelmuth** [comment]
Waiting for a new product change to successfully bump the version before I close this issue.
